# we need trusty because test-cmd depends on jq  version >= 1.5
dist : trusty
sudo: required

#env:
#  global:
#    secure: "h3UAsxDu3dTxNQlfRMeQ8ojH1YCUYFe+nnJGgTWLx+88zwPVtnlKi3cim9ODJ4Xfka+LrRDnSe/F+giodjTpBzAKnAHUF32e3YZJXCKcTGn3r0/o3mJZxb63fBAImLvjgbNrXAVlonbJkt6OV97hm839M6V8COBOoHieWe9e9O0vKC9kLXnM1em/rRmvPOVCAO0qoDyPBmh1tkgzn9pwMbOkVoyb0WYW2WMA8WBSRHCInoaF570vOnOYdprfB3xM4P79XOSb7LhcAuZRccnOYmUD33jcDiNI+Jg9fYSJgJNqcY3ogDQ1ly310Tlw3YQYB7VAisVL2BKymGoHAOmL1iXMhlzRdLkvwFuIJj+U6/pscdKrAtA8op5w1tWuqpsArmLi69J2tBQvwMqrpHDA/c35TnE7swQ6S4SstffhJBdPgYnPJTC5hR5vUtp8mFSEr9u5YIKG1GFTR5N/LKBroZtHODyPeuLUWUI7fYCpQGLFLP/H8UF0K8KgzMQnyWgI4jE7iA1tY/JQPTPhRE+u1TqOklFdtAgBloJ+hQNBkno1rbvGnYo9zQCF/RxZeQTPDbCUr9rsbQeofxxHkqs+ndDw/Y/gsvdUw6fI1oyu+ntgqLohWZZlhQzTER0W62oJTGVJF7tQMBGr7y+96YOgAuLU5zesqF5mP4st1g3Kq08="


language: go

go:
  - 1.6

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover


install:
  - mkdir -p $GOPATH/src/github.com/kubernetes-incubator
  - mv $GOPATH/src/github.com/kadel/kompose $GOPATH/src/github.com/kubernetes-incubator/kompose
  - cd $GOPATH/src/github.com/kubernetes-incubator/kompose

script:
  - make validate
  - make test-unit
  # collect all .coverprofile and report to coveralls.io
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci 
  #-repotoken $COVERALLS_TOKEN
  
  # make test-cmd requires kompose binary
  - make bin
  
  # $GOPATH/bin is in $PATH
  - mkdir -p $GOPATH/bin
  - cp kompose $GOPATH/bin/

  - make test-cmd
  
